export function getRandomPG13Prompt() {
  return prompts[Math.floor(Math.random() * prompts.length)];
}

const prompts = [
  "Tristan\u2019s favorite drink is ____",
  "You have 24 hours to prepare for a fight against Tristan.  What do you do and what do you bring?",
  "Define the axes on which Tristan rates his food.",
  "Tristan\u2019s dog is named Tiger. What would Tristan name his car?",
  "What is Tristan\u2019s go-to workout song?",
  "What does Tristan say his favorite movie is?",
  "Tristan has lost his water bottle again.  Where did he leave it this time?",
  "Tristan locked himself out of the house.  Whom does he call?",
  "Tristan has a sweet craving. What does he get from CVS?",
  "Tristan locked himself in his room! What does he do for three hours until one of his roommates rescues him (if)?",
  "Tristan's parents came to visit. Where does Tristan hide his stash?",
  "Tristan\u2019s childhood email was penguinpuppy0@gmail.com. To what animal is he most similar?",
  "Tristan\u2019s undergrad major was chemical engineering. If Tristan\u2019s discovered a new periodic table element, he would name it ___.",
  "What would Tristan's Everything Everywhere All At Once multiverse alter ego do?",
  "What archeyptal character would Tristan be in Lim's Anatomy?",
  "What would Tristan\u2019s superhero name be?",
  "If he could choose, what would Tristan\u2019s superpower be?", 
  "2 minutes left to BeReal!  What can you expect to see in Tristan\u2019s BeReal?",
  "Tristan\u2019s lab chore should be ___ instead of making PBS?",
  "If all crime were legal for 24 hours, Tristan would probably ____?",
  "Tristan's Thai nickname means Bucket. What would his street name be?",
  "Tristan has a problem set due in three days. Which three people from the Squad does he call upon to help?",
  "A food that Tristan absolutely will not eat is ____.",
  "Tristan can\u2019t find his name tag again! Where did Rob put it?",
  "Tristan\u2019s hidden talent is ____.",
  "Tristan\u2019s personality includes a unique *FLASH* of ____.",
  "Something Tristan got a trophy or award for as a kid was ____.",
  "If Tristan had an extra room in his apartment, he\u2019d probably use it for ____.",
  "If Tristan had a sandwich named after him, the two main ingredients would be ____.",
  "If Tristan could know one piece of information in the universe, it would be ____.",
  "Oh no, Tristan ate all the ___ again.",
  "What’s Tristan’s most expensive lab reagent purchase?",
  "What is the first thing Tristan does upon arriving to lab?",
  "What language is Tristan most likely to learn next?",
  "What hobby has Tristan always wanted to take up in his free time, when WeDon\u2019tWork?",
  "Nondh has cut his finger. What does Tristan do?",
  "If Tristan could travel to the past and switch seats with someone at Minn lab, whose seat would Tristan most likely take?",
  "Tristan is hungry on a Saturday. What unseasoned dish on Tristan's signature menu is the most palatable?",
  "What is Tristan as an ice cream flavor?",
  // "Tristan is hungover on a Saturday. What does he cook to cure it?",
  /* something Houston-related? Tristan is from Houston, and the Houston Rockets beat the Phillies in the World Series this year. */
];
